module ApplicationHelper


  def get_quote
    ["It's time to kick ass and chew bubblegum. And I'm all outta gum", "All your base are belong to us", "What is this, the testing department's day off or something?", "Do a barrel roll!", "It'sa me, Mario!", "Maybe the helicopter... maybe it's made of chocolate", "I need a weapon", "I'm no hero... never was", "Tell me Bats. What are you really scared of?", "It's dangerous to go alone. Take this", "I'm Commander Shepard and this is my favourite shop on the Citadel.", "Decapatatiiiiiiooooooonnnnnn!", "YOU WIN AGAIN, TECHNOLOGY!", "The last Metroid is in captivity, the galaxy is at peace", "You go to Mad Mel and say Hi from Scooter. ... and by that I mean you just go murder the crap outta him, ye hear?", "Power is like a drink. The more you have, the more you want.", "Men are but flesh and blood. They know their doom, but not the hour.", "Grand entrances are always impractical, that's what makes them grand.", "The answer lies in the heart of battle", "How are you holding up? BECAUSE I AM A POTATO!", "You fool! You gave cheese to a lactose intolerant volcano god!", "Stay a while, and listen!", "I'm-a-Wario! I’ma gonna win!", "You have died of dysentery", "This is your fault. I'm going to kill you. And all the cake is gone. You don't even care, do you?", "The right man in the wrong place can make all the difference in the world.", "First blood!", "C-c-c-combo breaker!", "Killtacular!", "Boomshakalaka!", "Why, that's the second biggest monkey head I've ever seen!", "Finish him!!", "Toasty!", "Get over here!", "Is a man not entitled to the sweat of his brow?", "Snake? Snake? SNAAAAAAAAKE!!!", "War. War never changes.", "You must construct additional pylons.", "In the year 200x a super robot named Mega Man was created.", "They call me Gato, I have metal joints. Beat me up and win 15 Silver Points.", "Wake me when you need me.", "Sonic Boom!", "Segaaaaaaaaaaaaaaaaaaaaa.", "Hadouken!", "Spy's sappin’ my sentry!", "Reticulating splines.", "Requiescat in pace.", "Wakka wakka wakka!", "Job's done.", "Show me your moves!", "REVIVE ME!", "It is pitch black. You are likely to be eaten by a grue.", "Fus-ro-dah!", "It’s super effective!", "The Kid just rages for a while."]

  end


end
